//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cidades.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atracoes
    {
        public int ID { get; set; }
        public Nullable<int> CidadeID { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string LinkImg { get; set; }
    
        public virtual Cidades Cidades { get; set; }
    }
}
